# Generated by Django 3.2 on 2023-05-15 10:01

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('products', '0009_product_discount_price'),
    ]

    operations = [
        migrations.RenameField(
            model_name='product',
            old_name='discount_price',
            new_name='original_price',
        ),
    ]
